name: "build"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the date
        id: date
        run: |
          echo "VERSION=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV
          echo "version=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_OUTPUT
          
      - name: Build and release devcontainer Multi-Platform
        uses: devcontainers/ci@v0.3.1900000338
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          imageName: ghcr.io/${{ github.repository }}
          platform: linux/amd64,linux/arm64
          push: always
          runCmd: echo "$HELLO - $WORLD"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.devcontainer/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/atg-ams/dh-next-dev:${{ env.VERSION }}
            ghcr.io/atg-ams/dh-next-dev:latest
